# Generated by Django 4.2 on 2023-04-13 08:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postingmodel',
            name='posting_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Created'),
            preserve_default=False,
        ),
    ]
