# Generated by Django 4.2 on 2023-04-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postingmodel',
            name='posting_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Posting Created'),
        ),
    ]
