# Generated by Django 4.2 on 2023-04-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postingmodel',
            name='posting_views',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
