# Generated by Django 4.2 on 2023-04-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posting", "0003_alter_postingmodel_posting_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postingmodel",
            name="posting_category",
            field=models.CharField(
                choices=[("뉴스피드", "뉴스피드"), ("자유게시판", "자유게시판")], max_length=10
            ),
        ),
    ]
