# Generated by Django 4.2 on 2023-04-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='birth',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Birth Created'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='blog',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
