# Generated by Django 4.2 on 2023-04-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='birth',
            field=models.DateTimeField(null=True, verbose_name='Birth Created'),
        ),
    ]
